---
title: Innherred Judo og BJJ
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  styret:
    title: Styret
    output: false
  trenere:
    title: Trenere
    output: false
  uploads:
    title: Uploads
    output: true
url: https://y7kim.github.io
email: ijudobjj@gmail.com
description: 'Innherred Judo og BJJ. Etablert i 2016. Opplev morsom og god trening
  for alle med erfarne kampsporttrenere. '
social:
- title: instagram
  url: http://instagram.com/innherredjudoogbjj
- title: youtube
  url: https://www.youtube.com/channel/UCYglIAHSwPWnh_Ipse9NyBg
- title: facebook
  url: https://www.facebook.com/innherredjudobjj/
address:
- line: Vårtun Kristne Oppvekstsenter
- line: Alstadhaugvegen 150
- line: 7607 Levanger
markdown: kramdown
permalink: pretty
